
services:
  gateway:
    image: cicdapplication/kenyaemr-gateway
    platform: linux/amd64
    restart: "unless-stopped"
    depends_on:
      - frontend
      - backend
    ports:
      - "80:80"

  frontend:
    image: cicdapplication/kenyaemr-frontend
    platform: linux/amd64
    restart: "unless-stopped"
    environment:
      SPA_PATH: /openmrs/spa
      API_URL: /openmrs
      SPA_CONFIG_URLS: /openmrs/spa/config/configs/kenyahmis-package/openmrs.config.json,/openmrs/spa/config/configs/kenyahmis-package/kenyaemr.config.json,/openmrs/spa/config/configs/kenyahmis-package/translations/translations.json
      SPA_DEFAULT_LOCALE: en
      SPA_PAGE_TITLE: "Taifa Care - KenyaEMR"
    volumes:
      - backend-spa-config:/usr/share/nginx/html/config
      - backend-spa-config:/usr/share/nginx/html/openmrs/spa
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/"]
      timeout: 5s
    depends_on:
      - backend

  backend:
    image: cicdapplication/kenyaemr-backend
    platform: linux/amd64
    restart: "unless-stopped"
    depends_on:
      - db
    environment:
      OMRS_CONFIG_MODULE_WEB_ADMIN: "true"
      OMRS_CONFIG_AUTO_UPDATE_DATABASE: "false"
      OMRS_CONFIG_CREATE_TABLES: "false"
      OMRS_CONFIG_CONNECTION_SERVER: db
      OMRS_CONFIG_CONNECTION_DATABASE: openmrs
      OMRS_CONFIG_CONNECTION_USERNAME: ${OMRS_DB_USER:-openmrs}
      OMRS_CONFIG_CONNECTION_PASSWORD: ${OMRS_DB_PASSWORD:-openmrs}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/openmrs"]
      timeout: 5s
    volumes:
      - openmrs-data:/openmrs/data
      - backend-spa-config:/openmrs/distribution/spa-config

  db:
    image: cicdapplication/kenyaemr-db
    platform: linux/amd64
    restart: "unless-stopped"
    command: "--character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --max_allowed_packet=1G --innodb-redo-log-capacity=1G"
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE:-openmrs}
      MYSQL_USER: ${OMRS_DB_USER:-openmrs}
      MYSQL_PASSWORD: ${OMRS_DB_PASSWORD:-openmrs}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-openmrs}

volumes:
  openmrs-data: ~
  backend-spa-config: ~

